import { chromium } from 'playwright'
const b = await chromium.launch({ channel: 'chrome' }); const ctx = await b.newContext({ viewport: { width: 1440, height: 1000 } })
const p = await ctx.newPage(); const errs = []; p.on('pageerror', (e) => errs.push(String(e)))
await p.goto('http://localhost:5178/', { waitUntil: 'networkidle' }); await p.waitForSelector('[data-id]')
await p.hover('[data-id="85:5353"]'); await p.waitForTimeout(200)
await p.screenshot({ path: 'extraction/shot-contact-hover.png', clip: { x: 340, y: 110, width: 1110, height: 260 } })
await p.click('[data-id="109:3774"]'); await p.waitForTimeout(500)
await p.screenshot({ path: 'extraction/shot-lead-dialog.png' })
await p.selectOption('.dialog select >> nth=2', '1–3 months'); await p.waitForTimeout(150)
await p.click('.dialog .btn-primary'); await p.waitForTimeout(400)
await p.click('[data-id="109:3831"]'); await p.waitForTimeout(300)
console.log('start pill now:', await p.locator('[data-id="109:5021"]').innerText())
await p.click('[data-id="85:3998"]'); await p.waitForTimeout(500)
await p.screenshot({ path: 'extraction/shot-contact-dialog.png' })
console.log('errors', errs)
await b.close()
