import { chromium } from 'playwright'
const S = process.argv[2]
const b = await chromium.launch({ channel: 'chrome' })
const p = await b.newPage({ viewport: { width: 1440, height: 1000 } })
const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('console', (m) => m.type() === 'error' && errs.push(m.text()))
await p.goto('http://localhost:5178/'); await p.waitForTimeout(500)
await p.click('[data-id="19:1215#off-19:1215"]'); await p.waitForTimeout(300)
await p.screenshot({ path: `${S}/t-agenda.png`, clip: { x: 324, y: 60, width: 1116, height: 780 } })
// add task
await p.click('text=Add task'); await p.waitForTimeout(300)
await p.screenshot({ path: `${S}/t-add.png` })
await p.selectOption('.dialog select', 'Measurement'); await p.click('.dialog .btn-primary'); await p.waitForTimeout(400)
await p.screenshot({ path: `${S}/t-agenda2.png`, clip: { x: 324, y: 300, width: 1116, height: 500 } })
await p.click('[data-id="19:1215#off-93:5727"]'); await p.waitForTimeout(300)
await p.screenshot({ path: `${S}/t-files.png`, fullPage: true })
await p.click('[aria-label="Grid view"]'); await p.waitForTimeout(200)
await p.screenshot({ path: `${S}/t-files-grid.png`, fullPage: true })
await p.click('[aria-label="Add files to Bathroom · Before Photos"]'); await p.waitForTimeout(300)
await p.setInputFiles('.dialog input[type=file]', [{ name: 'a.jpg', mimeType: 'image/jpeg', buffer: Buffer.from('x') }, { name: 'b.jpg', mimeType: 'image/jpeg', buffer: Buffer.from('x') }])
await p.click('.dialog .btn-primary'); await p.waitForTimeout(400)
await p.screenshot({ path: `${S}/t-files-up.png`, fullPage: true })
await p.click('[data-id="19:1215#off-19:1211"]'); await p.waitForTimeout(300)
console.log('overview files text', await p.locator('[data-id="93:7378"]').innerText(), 'warn', await p.locator('[data-id="93:7471"]').count(), 'agenda sub', await p.locator('[data-id="42:10920"]').innerText())
console.log('errors', errs)
await b.close()
